version: '2'

services:
 nexus:
  build: ./nexus
  ports:
    - "18081:8081"

 jenkins:
  build: ./jenkins
  ports:
    - "18080:8080"
  depends_on:
    - nexus
    - sonar
    - seleniumhub
  environment:
    - NEXUS_PORT=8081
    - SONAR_PORT=9000
    - SONAR_DB_PORT=5432

 sonar:
  build: ./sonar
  ports:
   - "19000:9000"
   - "5432:5432"
  depends_on:
    - sonardb
  environment:
   - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
   - SONARQUBE_JDBC_USERNAME=sonar
   - SONARQUBE_JDBC_PASSWORD=sonar

 sonardb:
  image: postgres
  environment:
   - POSTGRES_USER=sonar
   - POSTGRES_PASSWORD=sonar
  volumes:
    - /opt/postgres/data:/var/lib/postgresql/data

 seleniumhub:
  image: selenium/hub
  ports:
    - "4444:4444"

 firefox:
  image: selenium/node-firefox
  depends_on:
    - seleniumhub
  environment:
    - HUB_PORT_4444_TCP_ADDR=seleniumhub

 chrome:
  image: selenium/node-chrome
  depends_on:
    - seleniumhub
  environment:
    - HUB_PORT_4444_TCP_ADDR=seleniumhub
