version: '2'

networks:
  prodnetwork:
    driver: bridge

services:
 nexus:
  build: ./nexus
  ports:
    - "18081:8081"
  networks:
    - prodnetwork

 jenkins:
  build: ./jenkins
  ports:
    - "18080:8080"
  networks:
    - prodnetwork
  depends_on:
    - nexus
    - sonar
  environment:
    - NEXUS_PORT=8081
    - SONAR_PORT=9000
    - SONAR_DB_PORT=9092

 sonar:
  image: sonarqube
  ports:
   - "19000:9000"
   - "5432:5432"
  networks:
    - prodnetwork
  depends_on:
    - sonardb  
  environment:
   - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar

 sonardb:
  image: postgres
  networks:
    - prodnetwork
  environment:
    - POSTGRES_USER=sonar
    - POSTGRES_PASSWORD=sonar
  volumes:
    - postgresql:/var/lib/postgresql
    - postgresql_data:/var/lib/postgresql/data
