version: '2'

networks:
  prodnetwork:
    driver: bridge

services:
 nexus:
  build: sonatype/nexus
  ports:
    - "18081:8081"
  networks:
    - prodnetwork

 jenkins:
  build: jenkins
  ports:
    - "18080:8080"
  networks:
    - prodnetwork
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/local/bin/docker:/usr/bin/docker
    - /opt/jenkins/:/var/lib/jenkins/
  depends_on:
    - nexus
    - sonar
  environment:
    - NEXUS_PORT=8081
    - SONAR_PORT=9000
    - SONAR_DB_PORT=5432

 sonar:
  build: sonarqube
  ports:
    - "19000:9000"
    - "5432:5432"
  networks:
    - prodnetwork
  depends_on:
    - sonardb
  environment:
    - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
    - SONARQUBE_JDBC_USERNAME=sonar
    - SONARQUBE_JDBC_PASSWORD=sonar
  volumes:
    - /opt/sonarqube/conf
    - /opt/sonarqube/data
    - /opt/sonarqube/extensions
    - /opt/sonarqube/lib/bundled-plugins

 sonardb:
  networks:
    - prodnetwork
  image: postgres
  environment:
    - POSTGRES_USER=sonar
    - POSTGRES_PASSWORD=sonar
  volumes:
    - /opt/postgres/data:/var/lib/postgresql/data
