version: '2'

services:
  nexus:
    build: ./nexus
    ports:
      - "18081:8081"

  jenkins:
    build: ./jenkins
    ports:
      - "18080:8080"
    links:
      - nexus:nexus
      - sonar:sonar
      - selhub:hub

  sonar:
    build: ./sonar
    ports:
     - "19000:9000"
     - "5432:5432"
    environment:
     - SONARQUBE_JDBC_URL=jdbc:postgresql://localhost:5432/sonar

  db:
    image: postgres
    links:
      - sonar:sonar
    environment:
     - POSTGRES_USER=sonar
     - POSTGRES_PASSWORD=sonar

  selhub:
    image: selenium/hub
    ports:
      - 4444:4444

  nodeff:
    image: selenium/node-firefox-debug
    ports:
      - 5900
    links:
      - selhub:hub

  nodechrome:
    image: selenium/node-chrome-debug
    ports:
      - 5900
    links:
      - selhub:hub

  postgresql:
    image: sameersbn/postgresql:9.4-3
    environment:
      - DB_USER=gitlab
      - DB_PASS=password
      - DB_NAME=gitlabhq_production
    volumes:
      - /srv/docker/gitlab/postgresql:/var/lib/postgresql
      
  redis:
    image: sameersbn/redis:latest
    volumes:
      - /srv/docker/gitlab/redis:/var/lib/redis
