version: "2"

services:
 sonar:
  image: sonarqube
  ports:
    - "19000:9000"
    - "5432:5432"
  networks:
    - prodnetwork
  depends_on:
    - sonardb
  environment:
    - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
    - SONARQUBE_JDBC_USERNAME=sonar
    - SONARQUBE_JDBC_PASSWORD=sonar
  volumes:
    - /opt/sonarqube/conf
    - /opt/sonarqube/data
    - /opt/sonarqube/extensions
    - /opt/sonarqube/lib/bundled-plugins

 sonardb:
  networks:
    - prodnetwork
  image: postgres
  environment:
    - POSTGRES_USER=sonar
    - POSTGRES_PASSWORD=sonar
  volumes:
    - /opt/postgres/data

networks:
  prodnetwork:
    driver: bridge
